<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2017 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */



// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'mkk',
  'author' => 'Michael',
  'description' => '1.0',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'mkk',
  'published_date' => '2018-01-17 12:50:09',
  'type' => 'module',
  'version' => 1516193409,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'mkk',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'mkk_myCompany',
      'class' => 'mkk_myCompany',
      'path' => 'modules/mkk_myCompany/mkk_myCompany.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkk_mycompany_users_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkk_mycompany_project_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkk_mycompany_accounts_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/mkk_mycompany_am_projecttemplates_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkk_mycompany_usersMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkk_mycompany_projectMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkk_mycompany_accountsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/mkk_mycompany_am_projecttemplatesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/mkk_myCompany',
      'to' => 'modules/mkk_myCompany',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Users.php',
      'to_module' => 'Users',
      'language' => 'zh_CN',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'zh_CN',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Project.php',
      'to_module' => 'Project',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Project.php',
      'to_module' => 'Project',
      'language' => 'zh_CN',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'zh_CN',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_CN',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'zh_CN',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/AM_ProjectTemplates.php',
      'to_module' => 'AM_ProjectTemplates',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/AM_ProjectTemplates.php',
      'to_module' => 'AM_ProjectTemplates',
      'language' => 'zh_CN',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
      'language' => 'zh_CN',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_CN.lang.php',
      'to_module' => 'application',
      'language' => 'zh_CN',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_users_Users.php',
      'to_module' => 'Users',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_users_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_project_Project.php',
      'to_module' => 'Project',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_project_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_accounts_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_am_projecttemplates_AM_ProjectTemplates.php',
      'to_module' => 'AM_ProjectTemplates',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/mkk_mycompany_am_projecttemplates_mkk_myCompany.php',
      'to_module' => 'mkk_myCompany',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Users' => 'mkk_mycompany_users_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
        'Project' => 'mkk_mycompany_project_name',
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
        'Accounts' => 'mkk_mycompany_accounts_name',
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
        'AM_ProjectTemplates' => 'mkk_mycompany_am_projecttemplates_name',
      ),
    ),
  ),
);